from __future__ import annotations
import yaml

from .util import slug

GENERATED_HEADER = (
    "# Generated by the GeoDrops + Rachio Irrigation integration — "
    "edits are overwritten; configure in Settings → Devices & Services.\n"
)

# Defaults the wizard does not collect; the scheduler also has code defaults,
# but emitting them keeps the generated file self-describing.
_DEFAULT_TUNABLES = {
    "self_calibration_enabled": False,
}

# Soil-moisture bands. The scheduler's parse_config direct-indexes raw["bands"],
# so a generated config without this section is a KeyError on a real run. Values
# copied verbatim from the canonical scheduler's examples/config.example.yaml
# (agronomy, not site-specific — the wizard does not collect them). `low` is
# inclusive, `high` exclusive except the top band's inclusive 100.
_DEFAULT_BANDS = {
    "dry": {"low": 0, "high": 62},
    "dry_plus": {"low": 62, "high": 67},
    "moist": {"low": 67, "high": 76},
    "moist_plus": {"low": 76, "high": 87},
    "wet": {"low": 87, "high": 95},
    "wet_plus": {"low": 95, "high": 100},
}

# Drought-rating profiles. parse_config also direct-indexes
# raw["drought_profiles"]; the KEYS must match the drought_level select's
# options exactly. Values copied verbatim from the canonical scheduler's
# examples/config.example.yaml.
_DEFAULT_DROUGHT_PROFILES = {
    "Level 0 - Normal": {
        "target_offset": 0, "trigger_margin": 0, "runtime_scale": 1.0,
        "rain_skip_horizon_hours": 12, "end_anchor": "sunrise",
    },
    "Level 1 - Mild": {
        "target_offset": 0, "trigger_margin": 2, "runtime_scale": 0.9,
        "rain_skip_horizon_hours": 18, "end_anchor": "sunrise",
    },
    "Level 2 - Significant": {
        "target_offset": -1, "trigger_margin": 4, "runtime_scale": 0.8,
        "rain_skip_horizon_hours": 24, "end_anchor": "sunrise",
    },
    "Level 3 - Critical": {
        "target_offset": -1, "trigger_margin": 6, "runtime_scale": 0.7,
        "rain_skip_horizon_hours": 24, "end_anchor": "dawn",
    },
    "Level 4 - Emergency": {
        "target_offset": -2, "trigger_margin": 0, "runtime_scale": 0.5,
        "rain_skip_horizon_hours": 24, "end_anchor": "dawn",
    },
}


def _copy_bands() -> dict:
    return {name: dict(vals) for name, vals in _DEFAULT_BANDS.items()}


def _copy_drought_profiles() -> dict:
    return {name: dict(vals) for name, vals in _DEFAULT_DROUGHT_PROFILES.items()}


def _deep_merge(base: dict, overlay: dict) -> dict:
    out = dict(base)
    for k, v in overlay.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def generate_config(data: dict) -> str:
    tunables = dict(_DEFAULT_TUNABLES)
    tunables["self_calibration_enabled"] = bool(data.get("self_calibration_enabled"))

    overrides_raw = (data.get("advanced_overrides") or "").strip()
    if overrides_raw:
        try:
            parsed = yaml.safe_load(overrides_raw)
        except yaml.YAMLError as err:
            raise ValueError(f"advanced_overrides is not valid YAML: {err}") from err
        if parsed is not None:
            if not isinstance(parsed, dict):
                raise ValueError("advanced_overrides must be a YAML mapping of tunables")
            tunables = _deep_merge(tunables, parsed)

    zones = {}
    for z in data.get("zones", []):
        key = z["key"]
        zone = {k: v for k, v in z.items() if k != "key"}
        zone.setdefault(
            "exclude_boolean", f"switch.geodrops_rachio_{slug(key)}_exclude")
        zones[key] = zone

    doc = {
        "homeassistant": dict(data.get("bindings", {})),
        "tunables": tunables,
        "bands": _copy_bands(),
        "drought_profiles": _copy_drought_profiles(),
        "zones": zones,
    }
    return GENERATED_HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
