from __future__ import annotations
import yaml

GENERATED_HEADER = (
    "# Generated by the GeoDrops + Rachio Irrigation integration — "
    "edits are overwritten; configure in Settings → Devices & Services.\n"
)

# Defaults the wizard does not collect; the scheduler also has code defaults,
# but emitting them keeps the generated file self-describing.
_DEFAULT_TUNABLES = {
    "self_calibration_enabled": False,
}


def _deep_merge(base: dict, overlay: dict) -> dict:
    out = dict(base)
    for k, v in overlay.items():
        if isinstance(v, dict) and isinstance(out.get(k), dict):
            out[k] = _deep_merge(out[k], v)
        else:
            out[k] = v
    return out


def generate_config(data: dict) -> str:
    tunables = dict(_DEFAULT_TUNABLES)
    tunables["self_calibration_enabled"] = bool(data.get("self_calibration_enabled"))

    overrides_raw = (data.get("advanced_overrides") or "").strip()
    if overrides_raw:
        try:
            parsed = yaml.safe_load(overrides_raw)
        except yaml.YAMLError as err:
            raise ValueError(f"advanced_overrides is not valid YAML: {err}") from err
        if parsed is not None:
            if not isinstance(parsed, dict):
                raise ValueError("advanced_overrides must be a YAML mapping of tunables")
            tunables = _deep_merge(tunables, parsed)

    zones = {}
    for z in data.get("zones", []):
        key = z["key"]
        zones[key] = {k: v for k, v in z.items() if k != "key"}

    doc = {
        "homeassistant": dict(data.get("bindings", {})),
        "tunables": tunables,
        "zones": zones,
    }
    return GENERATED_HEADER + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
